Proyecto/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from myapp import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView
from myapp.views import editar_tramite,reset_password,send_password_reset_email
from django.conf.urls import handler404

handler404 = 'myapp.views.custom_404'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login_view, name='login'),
    path('logout/', login_required(views.CustomLogoutView.as_view()), name='logout'),
    path('dashboardhome/', login_required(views.DashboardViewHome), name='dashboardhome'),
    path('user_register/',login_required(views.register), name='user_register'),
    path('perfil/', login_required(views.user_profile), name='user_profile'),
    path('user-list/',login_required(views.user_list), name='user_list'),
    path('user_edit/<int:user_id>/', login_required(views.user_edit), name='user_edit'),
    path('tramite_register/', login_required(views.crear_tramite), name='tramite_register'),
    path('tramite_list/', login_required(views.listar_tramites), name='tramite_list'),
    path('tramite_edit/<int:pk>/', login_required(editar_tramite), name='tramite_edit'),
    path('send_password_reset/<int:user_id>/', login_required(send_password_reset_email), name='send_password_reset_email'),
    path('reset-password/<uidb64>/<token>/', login_required(PasswordResetConfirmView.as_view()), name='password_reset_confirm'),
    path('reset-password/<int:user_id>/', reset_password, name='reset_password'),
    path('tramite_subir_documento/<int:tramite>/', login_required(views.subir_documento), name='tramite_subir_documento'),
    path('documentos/<int:documento_id>/', login_required(views.ver_contenido_pdf), name='ver_contenido_pdf'),
    path('tramite_agregar_observacion/<int:tramite>/', login_required(views.tramite_agregar_observacion), name='tramite_agregar_observacion'),
    path('tramite_ver_observaciones_tramite/<int:tramite_id>/', login_required(views.tramite_ver_observaciones_tramite), name='tramite_ver_observaciones_tramite'),
    path('afiliado_tramite_list/', login_required(views.lista_tramites_afiliados), name='afiliado_tramite_list'),
    path('afiliado_list/', login_required(views.lista_afiliado), name='afiliado_list'),
    path('afiliado_register/<int:tramite_id>/', login_required(views.afiliado_register), name='afiliado_register'),
    path('afiliado_edit/<int:pk>/', login_required(views.editar_afiliado), name='afiliado_edit'),
    path('afiliado_observation/<int:afiliado>/', login_required(views.agregar_observacion), name='afiliado_observation'),
    path('afiliado_ver_observaciones/<int:afiliado_id>/', login_required(views.afiliado_ver_observaciones), name='afiliado_ver_observaciones'),
    path('vehiculos_tramite_list/', views.vehiculos_tramite_list, name='vehiculos_tramite_list'),
    path('vehiculos_register/<int:afiliado_id>/', views.vehiculos_register, name='vehiculos_register'),
    path('vehiculo_list/', views.listar_vehiculos, name='vehiculo_list'),
    path('vehiculos_afiliado_tramite/<int:afiliado_id>/', views.vehiculos_afiliado_tramite, name='vehiculos_afiliado_tramite'),
    path('vehiculo_edit/<int:vehiculo_id>/', views.editar_vehiculo, name='vehiculo_edit'),
    path('vehiculo_informacion/<int:vehiculo_id>/', views.ver_informacion_vehiculo, name='vehiculo_informacion'),
    path('vehiculo_agregar_observaciones/<int:vehiculo_id>/', views.agregar_observaciones, name='vehiculo_agregar_observaciones'),
    path('vehiculo_ver_observaciones/<int:vehiculo_id>/', views.ver_observaciones, name='vehiculo_ver_observaciones'),
    path('tarjeta_operacion_tramite/', views.tarjeta_operacion_tramite, name='tarjeta_operacion_tramite'),
    path('tarjeta_operacion_vehiculo/<int:afiliado_id>/', views.tarjeta_operacion_vehiculo, name='tarjeta_operacion_vehiculo'),
    path('generar_tarjeta_operacion/<int:vehiculo_id>/', views.generar_tarjeta_operacion, name='generar_tarjeta_operacion'),
    path('generar_tarjeta_operacion/<int:vehiculo_id>/', views.generar_tarjeta_operacion, name='generar_tarjeta_operacion'),
    path('detalle_tarjeta_operacion_pdf/<int:tarjeta_operacion_id>/', views.detalle_tarjeta_operacion_pdf, name='detalle_tarjeta_operacion_pdf'),
    path('actualizar_tarjeta_operacion/<int:vehiculo_id>/', views.actualizar_tarjeta_operacion, name='actualizar_tarjeta_operacion'),
    path('verificar_datos_vehiculo/<int:vehiculo_id>/', views.verificar_datos_vehiculo, name='verificar_datos_vehiculo'),
    path('ver_tarjeta_operacion_pdf/<int:tarjeta_operacion_id>/', views.ver_tarjeta_operacion_pdf, name='ver_tarjeta_operacion_pdf'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

class Tipo_tramite(models.Model):
    nom_tipo_de_tramite = models.CharField(max_length=255)
    def __str__(self):
        return self.nom_tipo_de_tramite
    

class Tramite(models.Model):
    num_tramite = models.CharField(max_length=20, unique=True, blank=True, null=True)
    fecha = models.DateField()
    hora = models.TimeField()
    solicitante = models.CharField(max_length=255)
    num_fojas = models.IntegerField()
    tipo_de_tramite = models.ForeignKey(Tipo_tramite, on_delete=models.CASCADE, null=True, blank=True)
    fecha_entrega_form_obs = models.DateField()
    ESTADO_CHOICES = [
        ('Ingresado', 'Ingresado'),
        ('Anulado', 'Anulado'),
        ('Entregado', 'Entregado'),
        ('Proceso', 'Proceso')
        ]
    estado = models.CharField(max_length=50, choices=ESTADO_CHOICES)
    comentario = models.TextField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def save(self, *args, **kwargs):
        if not self.id:
            self.id = self.num_tramite = max(1500, Tramite.objects.all().count() + 1500)

        super().save(*args, **kwargs)
    def __str__(self):
        return self.num_tramite
    

class Documento(models.Model):
    nombre_archivo = models.CharField(max_length=255)
    archivo = models.FileField(upload_to='pdf/', blank=True, null=True)
    tramite = models.ForeignKey(Tramite, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_archivo
    
class Observaciones(models.Model):
    espacio = models.TextField()
    fecha_obs = models.DateField()
    hora_obs = models.TimeField()
    tramite = models.ForeignKey('Tramite', on_delete=models.CASCADE)

    def __str__(self):
        return f'Observación para Trámite {self.tramite.num_tramite}'


class Razon_social(models.Model):
    razon_social_operador = models.CharField(max_length=100)
    def __str__(self):
        return self.razon_social_operador
    
    
class Afiliado(models.Model):
    tramite = models.ForeignKey(Tramite, on_delete=models.CASCADE)
    nombre_asociacion = models.CharField(max_length=100)
    razon_social_operador = models.ForeignKey(Razon_social, on_delete=models.CASCADE, null=True, blank=True)
    fecha = models.DateField()
    hora = models.TimeField()
    ubicacion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre_asociacion

class Observaciones_afiliados(models.Model):
    espacio = models.TextField()
    fecha_obs = models.DateField()
    hora_obs = models.TimeField()
    afiliado = models.ForeignKey('Afiliado', on_delete=models.CASCADE)

    def __str__(self):
        return f'Observación para Afiliado {self.afiliado.nombre_asociacion}'
    
from django.db import models
class Marca_vehiculo(models.Model):
    marca_vehiculo = models.CharField(max_length=100)
    def __str__(self):
        return self.marca_vehiculo
    
     
class Vehiculo(models.Model):
    afiliado = models.ForeignKey(Afiliado, on_delete=models.CASCADE)
    marca_vehiculo = models.ForeignKey(Marca_vehiculo, on_delete=models.CASCADE, null=True, blank=True)
    placa = models.CharField(max_length=20)
    botic = models.CharField(max_length=100)
    conductor = models.CharField(max_length=100)
    fecha_ve = models.DateField()
    fecha_vvv = models.DateField()
    hora_ve = models.TimeField()
    categoria = models.CharField(max_length=100)
    capacidad = models.IntegerField()
    tipo_de_vehiculo = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    chasis = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='vehiculos/', null=True, blank=True)
    tipo_tarjeta = models.CharField(max_length=100)
    validez = models.CharField(max_length=100)
    gestion = models.CharField(max_length=100)
    rutas = models.TextField()

    def __str__(self):
        return self.placa

class Observaciones_vehiculos(models.Model):
    espacio = models.TextField()
    fecha_obs = models.DateField()
    hora_obs = models.TimeField()
    vehiculo = models.ForeignKey('Vehiculo', on_delete=models.CASCADE)

    def __str__(self):
        return f'Observación para vehiculo {self.vehiculo.placa}'

from django.db import models
class TarjetaOperacion(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='pdf_tarjetas_operacion/')

myapp/templates/afiliado_ver_observaciones.html
{% extends  'index_master.html' %}
{% load static %}

<body>
    {% block content %}
    <div class="right_col" role="main">

    <h2>Observaciones para afiliado {{ afiliado.nombre_asociacion }}</h2>
    <ul>
        {% for observacion in observaciones %}
            <li>{{ observacion.espacio }} - {{ observacion.fecha_obs }} {{ observacion.hora_obs }}</li>
        {% endfor %}
    </ul>
    {% endblock %}
</body>
d

myapp/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Tu código de encabezado aquí -->
</head>
<body>
    {% include 'navbar2.html' %}
    {% include 'sidebar.html' %}
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

myapp/templates/editar_tramite.html
{% extends 'base.html' %}

{% block content %}
    <h2>Editar Trámite</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
{% endblock %}

myapp/templates/editar_usuario.html
{% extends 'base.html' %}
{% load static %}
<body>
  {% block content %}
  <link rel="stylesheet" href="{% static 'css/editar_usuario.css' %}">

  <h2>Editar Usuario: {{ usuario.username }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Guardar Cambios</button>
  </form>
{% endblock %}

</body>

myapp/templates/listar_tramites.html
<<<<<<< HEAD
{% extends 'base.html' %}
{% load static %}
<body>
   <div class="ewsa">
    {% block content %}
    <link rel="stylesheet" href="{% static 'css/listar_tramites.css' %}">
=======
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
         .modal {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        }

        .modal-content {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
        }
        .documento-indicador {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            display: inline-block;
            margin-right: 5px;
        }

        .documento-existente {
            background-color: green;
        }

        .sin-documento {
            background-color: red;
        }
    </style>
    <title>Listar Trámites</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
>>>>>>> 1eea7760110c5179c830951cb798bc98e55ff42f
    <form method="get" action="{% url 'listar_tramites' %}">
        <input type="text" name="q" value="{{ query }}" placeholder="Buscar">
        <button type="submit">Buscar</button>
    </form>

<<<<<<< HEAD
=======
    <!-- Contenido principal -->
    <div class="container mt-5">
       <!-- Botón para abrir la ventana modal -->
        <button id="open-modal">Subir documento</button>
        <div class="modal" id="modal">
            <div class="modal-content">
                <!-- Contenido del formulario -->
                <form method="post" action="{% url 'listar_tramites' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Guardar</button>
                </form>
                <!-- Botón para cerrar la ventana modal -->
                <button id="close-modal">Cerrar Ventana Modal</button>
            </div>
        </div>
    </div>

    <script>
        // Controlar el estado de la ventana modal con JavaScript
        const openModalBtn = document.getElementById('open-modal');
        const closeModalBtn = document.getElementById('close-modal');
        const modal = document.getElementById('modal');

        openModalBtn.addEventListener('click', () => {
            modal.style.display = 'flex';
        });

        closeModalBtn.addEventListener('click', () => {
            modal.style.display = 'none';
        });
    </script>

>>>>>>> 1eea7760110c5179c830951cb798bc98e55ff42f
    <h2>Listado de Trámites</h2>
    <table border="1">
        <thead>
            <tr>
                <th>Número de Trámite</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Solicitante</th>
                <th>Número de Fojas</th>
                <th>Tipo de Tramite</th>
                <th>Fecha de Entrega con Observaciones</th>
                <th>Estado</th>
                <th>Comentario</th>
                <th>Documento Subido</th>
                <th>Obciones</th>
            </tr>
        </thead>
        <tbody>
            {% for tramite in tramites %}
                <tr>
                    <td>{{ tramite.num_tramite }}</td>
                    <td>{{ tramite.fecha }}</td>
                    <td>{{ tramite.hora }}</td>
                    <td>{{ tramite.solicitante }}</td>
                    <td>{{ tramite.num_fojas }}</td>
                    <td>{{ tramite.tipo_de_tramite }}</td>
                    <td>{{ tramite.fecha_entrega_form_obs }}</td>
                    <td>{{ tramite.estado }}</td>
                    <td>{{ tramite.comentario }}</td>
                    <td>
                        <span class="documento-indicador {% if tramite.documento_set.all %}documento-existente{% else %}sin-documento{% endif %}"></span>
                        {% if tramite.documento_set.all %}
                            {{ tramite.documento_set.first.nombre_archivo }}
                        {% else %}
                            Sin Documento
                        {% endif %}
                    </td>
<<<<<<< HEAD
                    <td class="edit-options">
                        <a href="{% url 'editar_tramite' pk=tramite.pk %}" class="editar">Editar</a>,
                        <a href="{% url 'subir_documento' tramite=tramite.id %}" class="subir">Subir Documento</a>
=======
                    <td>
                        (<a href="{% url 'editar_tramite' pk=tramite.pk %}">Editar</a>),
                        (<a href="{% url 'subir_documento' tramite_id=tramite.id %}">Subir Documento</a>)
>>>>>>> 1eea7760110c5179c830951cb798bc98e55ff42f
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endblock %}
<<<<<<< HEAD
</div>  
</body>
</html>
=======
</body>
</html>
>>>>>>> 1eea7760110c5179c830951cb798bc98e55ff42f

myapp/templates/login.html
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"> 
    <div class="login-container background-image">
        <div class="login-form-container">
            <img src="{% static 'imagen/logo.webp' %}" alt="Logo" class="logo mb-4">
            <h2 class="mb-4">Login</h2>
            <form method="post" action="{% url 'login' %}" class="login-form">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.username.label_tag }}
                    {{ form.username}}
                </div>
                <div class="mb-3">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/navbar2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/navbar2.css' %}">
</head>
<body>
  <nav>
    <div class="navbar">
        <p class="tex1">USUARIO: {{ user.username }}  </p>
        <p class="tex2">   GRUPO: {{ user_group }}</p>
        <a class="dashboard" href="{% url 'dashboardhome' %}">Dashboard</a>
        <div class="logout">
          {% if user.is_authenticated %}
          <a class="active" href="{% url 'logout' %}">Cerrar sesión</a>
          {% endif %}
        </div>
    </div>
  </nav>
</body>
</html>

myapp/templates/register.html
{% extends 'base.html' %}
{% load static %}

<body>
    {% block content %}
    <div class="containe">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <title>Tu Proyecto</title>
    <h2>Registro</h2>
    {% for message in messages %}
        <div class="{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    <form method="post" action="{% url 'register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
</div>   
{% endblock %}
</body>

myapp/templates/sidebar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <title>Tu Proyecto</title>
</head>
<body>
        <div class="sidebar">
                    {% if user_group %}
              {% if user_group == "Administradores" %}
              
              <li><a href="{% url 'register' %}">Registrar usuarios</a></li>
              <li><a href="{% url 'user_list' %}">lista de usuario</a></li>              
                <li>
                  <a href="{% url 'register_tramite' %}">Registrar los tramites</a>
                </li>
                <li>
                  <a href="{% url 'listar_tramites' %}">listar tramites</a>
                </li>           
                <li>
                  <a href="{% url 'listar_documentos' %}">listar documentos</a>
                </li>
                <li>
                  <a href="">Registrar afiliados</a>
                </li>    
                <li>
                  <a href="">Editar afiliados</a>
                </li>    
                <li>
                  <a href="">Registrar vehiulos</a>
                </li>    
                <li>
                  <a href="">Editar vehiculos</a>
                </li>    
                <li>
                  <a href="">Generar tarjeta de operacion </a>
                </li>       
                <li>
                  <a href="">Reportes</a>
                </li>               
              {% elif user_group == "Tecnicos" %}
              <li>
                <a href="{% url 'register_tramite' %}">Registrar los tramites</a>
              </li>    
              <li>
                <a href="{% url 'listar_tramites' %}">listar tramites</a>
              </li> 
              <li>
                <a href="{% url 'listar_documentos' %}">listar documentos</a>
              </li>
              <li>
                <a href="">Registrar afiliados</a>
              </li>    
              <li>
                <a href="">Registrar vehiulos</a>
              </li>    
              <li>
                <a href="">Buscador de tramites</a>
              </li>    
              <li>
                <a href="">Buscador de afiliados</a>
              </li>    
              <li>
                <a href="">Buscador de vehivulos</a>
              </li>    
              <li>
                <a href="">Buscador de tarjetas de operacion</a>
              </li>                
                  <p>Opciones para Group2</p>
              {% elif user_group == "Secretarias" %}
              <li>
                <a href="">Registrar vehiulos</a>
              </li>    
              <li>
                <a href="">Buscador de tramites</a>
              </li>    
              <li>
                <a href="">Buscador de afiliados</a>
              </li>    
              <li>
                <a href="">Buscador de vehivulos</a>
              </li>    
              <li>
                <a href="">Buscador de tarjetas de operacion</a>
              </li>                
                  <p>Opciones para Group2</p>
              {% endif %}
          {% endif %}
          <!-- Otro contenido del dashboard -->
        </div>

<!-- Resto del contenido del cuerpo de la página -->

</body>
</html>

myapp/templates/tarjeta_operacion_tramite.html
{% extends 'index_master.html' %}
{% load static %}

{% block content %}
<div class="right_col" role="main">
    <link rel="stylesheet" href="{% static 'css/vehiculos_tramite_list.css' %}">

    <h1>Lista de trámites con afiliado</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Número de Trámite</th>
                    <th>Nombre del Afiliado</th>
                    <th>Vehiculos Registrados</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for dato in datos_tabla %}
                <tr>
                    <td>{{ dato.numero_tramite }}</td>
                    <td>{{ dato.nombre_afiliado }}</td>
                    <td>{{ dato.vehiculos_registrados }}</td>
                    <td>
                        <a href="{% url 'tarjeta_operacion_vehiculo' afiliado_id=dato.afiliado_id %}" class="btn btn-primary">Ver Vehículos</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

myapp/templates/tramite_list.html
{% extends  'index_master.html' %}
{% load static %}
<body>
   <div class="ewsa">
    {% block content %}
    <div class="right_col" role="main">

    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
    <link rel="stylesheet" href="{% static 'css/listar_tramites.css' %}">


    <h2>Listado de Trámites</h2>
    <form method="get" action="{% url 'tramite_list' %}">
        <input type="text" name="q" value="{{ query }}" placeholder="Buscar">
        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i>
        </button>
    </form>
    <table border="1">
        <thead>
            <tr>
                <th>N° de Trámite</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Solicitante</th>
                <th>N° de Fojas</th>
                <th>Tipo de Tramite</th>
                <th>Estado</th>
                <th>Comentario</th>
                <th>Documento Subido</th>
                <th>Obciones</th>
            </tr>
        </thead>
        <tbody>
            {% for tramite in tramites %}
                <tr>
                    <td>{{ tramite.num_tramite }}</td>
                    <td>{{ tramite.fecha }}</td>
                    <td>{{ tramite.hora }}</td>
                    <td>{{ tramite.solicitante }}</td>
                    <td>{{ tramite.num_fojas }}</td>
                    <td>{{ tramite.tipo_de_tramite }}</td>
                    <td>{{ tramite.estado }}</td>
                    <td>{{ tramite.comentario }}</td>
                    <td>
                        <span class="documento-indicador {% if tramite.documento_set.all %}documento-existente{% else %}sin-documento{% endif %}"></span>
                        {% if tramite.documento_set.all %}
                            <a href="{% url 'ver_contenido_pdf' documento_id=tramite.documento_set.first.id %}" target="_blank">{{ tramite.documento_set.first.nombre_archivo }}</a>
                        {% else %}
                            Sin Documento
                        {% endif %}
                    </td>
                    <td class="edit-options">
                        <div class="col-lg-4 col-md-4 flex-container">
                            {% if user.is_superuser %}
                            <a href="{% url 'tramite_edit' pk=tramite.pk %}" class="editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            {% endif %}
                            
                        <a href="{% url 'tramite_subir_documento' tramite=tramite.id %}" class="subir"><i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                        </a>
                        <a href="{% url 'tramite_agregar_observacion' tramite=tramite.id %}" class="agregar-observacion"><i class="fa fa-list-ul" aria-hidden="true"></i>
                        </a>
                        <a href="{% url 'tramite_ver_observaciones_tramite' tramite_id=tramite.id %}"><i class="fa fa-eye" aria-hidden="true"></i>
                        </a>
                    </div>   
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
    <span class="step-links">
        {% if tramites.has_previous %}
            <a href="?page=1">&laquo; </a>
        {% endif %}

        <span class="current">
            Página {{ tramites.number }} de {{ tramites.paginator.num_pages }}.
        </span>

        {% if tramites.has_next %}
            <a href="?page={{ tramites.paginator.num_pages }}">&raquo;</a>
        {% endif %}
    </span>
</div>
    {% endblock %}
</div>  
</body>
</html>

myapp/templates/vehiculo_edit.html
{% extends 'index_master.html' %}

{% block content %}
<div class="right_col" role="main">

  <h1>Editar Vehículo</h1>
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div class="{{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </div>
  {% endif %}
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>
</div>
{% endblock %}

myapp/templates/vehiculo_ver_observaciones.html
{% extends  'index_master.html' %}
{% load static %}

<body>
    {% block content %}
    <div class="right_col" role="main">

    <h2>Observaciones para vehiculo {{ vehiculo.matricula }}</h2>
    <ul>
        {% for observacion in observaciones %}
            <li>{{ observacion.espacio }} - {{ observacion.fecha_obs }} {{ observacion.hora_obs }}</li>
        {% endfor %}
    </ul>
    {% endblock %}
</body>
d